services:
  air-pollution-service:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      AIR_POLLUTION_FILE: "/air-pollution-service/data.csv"
      SERVER_PORT: "8080"
      BLA: BLA
    volumes:
      - "./air-pollution.csv:/air-pollution-service/data.csv"
