// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/countries/": {
            "get": {
                "description": "TODO",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "country"
                ],
                "summary": "TODO",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/CountryResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    }
                }
            }
        },
        "/countries/{name}": {
            "get": {
                "description": "TODO",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "country"
                ],
                "summary": "TODO",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name of the country",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CountryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    }
                }
            }
        },
        "/emissions/country/": {
            "get": {
                "description": "TODO",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "emission country"
                ],
                "summary": "TODO",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/AirPollutionEmissionsResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    }
                }
            }
        },
        "/emissions/country/{name}": {
            "get": {
                "description": "TODO",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "emission country"
                ],
                "summary": "TODO",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name of the country",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AirPollutionEmissionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    }
                }
            }
        },
        "/emissions/year/": {
            "get": {
                "description": "TODO",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "emission year"
                ],
                "summary": "TODO",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/AirPollutionEmissionsResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    }
                }
            }
        },
        "/emissions/year/{year}": {
            "get": {
                "description": "TODO",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "emission year"
                ],
                "summary": "TODO",
                "parameters": [
                    {
                        "type": "string",
                        "description": "year",
                        "name": "year",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AirPollutionEmissionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AirPollutionEmissionsResponse": {
            "type": "object",
            "properties": {
                "ammonia_emissions": {
                    "$ref": "#/definitions/AirPollutionResponse"
                },
                "black_carbon_emissions": {
                    "$ref": "#/definitions/AirPollutionResponse"
                },
                "carbon_monoxide_emissions": {
                    "$ref": "#/definitions/AirPollutionResponse"
                },
                "nmvoc_emissions": {
                    "$ref": "#/definitions/AirPollutionResponse"
                },
                "nox_emissions": {
                    "$ref": "#/definitions/AirPollutionResponse"
                },
                "organic_carbon_emissions": {
                    "$ref": "#/definitions/AirPollutionResponse"
                },
                "sulphur_dioxide_emissions": {
                    "$ref": "#/definitions/AirPollutionResponse"
                }
            }
        },
        "AirPollutionResponse": {
            "type": "object",
            "properties": {
                "average": {
                    "type": "number"
                },
                "median": {
                    "type": "number"
                },
                "standard_deviation": {
                    "type": "number"
                }
            }
        },
        "CountryResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "ErrResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
