definitions:
  AirPollutionCountries:
    properties:
      countries:
        additionalProperties:
          $ref: '#/definitions/AirPollutionResponse'
        type: object
    type: object
  AirPollutionResponse:
    properties:
      ammonia_emissions:
        $ref: '#/definitions/EmissionsResponse'
      black_carbon_emissions:
        $ref: '#/definitions/EmissionsResponse'
      carbon_monoxide_emissions:
        $ref: '#/definitions/EmissionsResponse'
      nmvoc_emissions:
        $ref: '#/definitions/EmissionsResponse'
      nox_emissions:
        $ref: '#/definitions/EmissionsResponse'
      organic_carbon_emissions:
        $ref: '#/definitions/EmissionsResponse'
      sulphur_dioxide_emissions:
        $ref: '#/definitions/EmissionsResponse'
    type: object
  AirPollutionYears:
    properties:
      years:
        additionalProperties:
          $ref: '#/definitions/AirPollutionResponse'
        type: object
    type: object
  CountryResponse:
    properties:
      code:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  EmissionsResponse:
    properties:
      average:
        type: number
      median:
        type: number
      standard_deviation:
        type: number
    type: object
  ErrResponse:
    properties:
      code:
        example: 404
        type: integer
      error:
        example: The requested resource was not found on the server.
        type: string
      text:
        type: string
    type: object
info:
  contact: {}
paths:
  /countries/:
    get:
      description: Returns all countries available in the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/CountryResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrResponse'
      summary: List all available countries
      tags:
      - country
  /countries/{id}:
    get:
      description: Returns a single country by id
      parameters:
      - description: ID of the country, case-insensitive
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CountryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrResponse'
      summary: Get country by its id
      tags:
      - country
  /emissions/country/:
    get:
      description: All historical emissions data of each country accumulated over
        all years
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AirPollutionCountries'
      summary: List emissions of each country accumulated over all years
      tags:
      - emission country
  /emissions/country/{id}:
    get:
      description: All historical emissions data of a country accumulated over all
        years, available in the database
      parameters:
      - description: id of the country, case-insensitive
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AirPollutionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrResponse'
      summary: Get emissions of all years accumulated for a single country
      tags:
      - emission country
  /emissions/year/:
    get:
      description: All historical emissions data of each year accumulated over all
        countries
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AirPollutionYears'
      summary: List emissions of each year accumulated over all countries
      tags:
      - emission year
  /emissions/year/{year}:
    get:
      description: All historical emissions data of a year accumulated over all countries,
        available in the database
      parameters:
      - description: year
        in: path
        name: year
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AirPollutionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrResponse'
      summary: Get emissions of all countries accumulated for a single year
      tags:
      - emission year
swagger: "2.0"
