name: Build Docker image and publish to GHCR

on:
  push:
    branches:
      main
    tags:
      v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hbtgmbh/air-pollution-service
  BUILD_ID: ${{github.run_number}}

jobs:
  test:
    name: Test and lint
    uses: HBTGmbH/air-pollution-service/.github/workflows/test.yml@main

  build:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_ID }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_ID }}
